version: '3'
services:
  nginx:
    image: nginx:alpine
    container_name: monzo_balance_nginx_1
    restart: unless-stopped
    tty: true
    env_file: '.env'
    ports:
      - "5678:80"
    volumes:
      - webroot:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    image: php:7-fpm-alpine
    container_name: monzo_balance_php_1
    restart: unless-stopped
    tty: true
    env_file: '.env'
    volumes:
      - webroot:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  webroot:
